# command_sequence index
# [1] command:
#   1. takeoff = Taking off sequence
#   2. hold = Wait for certain time
#   3. goto = Move to location
#   4. goto_velocity = Move to location with velocity control
#   5. external = Wait for external command
#   6. land = Landing sequence
# [2] to wait before the next command:
#   1. conc = Go to the next command without waiting for this
#   2. wait = Wait for this command
# [3] drone number involved
#   1. "all"
#   2. "cfX" = split the cfs by underscore etc "cf1_cf2_cf3"
#   3. "ext" = external module will give
# [4] duration (only applicable to hold) in ms
# [5] pose in XYZ "1 1 1"

command_sequence: [
  "takeoff", "wait", "all", "", "",
  # "hold", "wait", "all", "7.0", "",
  "goto_velocity", "conc", "cf1", "", "1 1 1 0.707",
  "goto_velocity", "conc", "cf2", "", "1 0 1 0.707",
  "goto_velocity", "wait", "cf3", "", "1 -1 1 0.707",
  "hold", "wait", "all", "7.0", "",
  # "goto_velocity", "wait", "cf1 cf2", "", "1.2 1.2 1 0.707",
  # "goto_velocity", "wait", "cf3 cf4", "", "1.2 -1.2 1 0.707",
  # "goto", "wait", "cf1 cf2", "", "-1 0 1 -0.707",
  # "goto", "wait", "cf1 cf2", "", "-1 1 1 -0.707",
  # "goto", "wait", "cf3 cf4", "", "0 1 1 0.707",
  # "land", "wait", "cf1 cf2", "", "",
  "land", "wait", "all", "", ""
]
# command_sequence: [""]
queue_size: 20
trajectory_parameters:
  max_velocity: 0.8
  reached_threshold: 0.15
  takeoff_land_velocity: 0.5
  takeoff_height: 1.0
  planning_rate: 5.0
  communication_radius: 5.0
  protected_zone: 0.1
  planning_horizon_scale: 3.0
april_tag_parameters:
  # 45 degs pointing downwards
  camera_rotation: [-0.3826834, 0, 0, 0.9238795] # x,y,z,w
  time_threshold: 0.100
  eliminate_threshold: 2.00

environment:
  obstacles: 
    obs0:
      type: "wall-disjointed"
      height: [0.0, 2.5]
      points: [
        8.0, 3.0, 
        8.0, 8.5,
        13.0, 8.5,
        13.0, 5.5
      ]
    obs1:
      type: "wall-disjointed"
      height: [0.0, 2.5]
      points: [
        8.0, 17.0, 
        8.0, 11.5,
        13.0, 11.5,
        13.0, 14.5
      ]

# https://github.com/rgov/apriltag-pdfs
april_tags:
  id000:
    id: 0
    location: [0.1035, -0.182]
    purpose: relocalization
  id001:
    id: 1
    location: [0.5035, -0.5825]
    purpose: relocalization